### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by Jack0211** [Begeassgit/RepairWeb#19]
![image](https://user-images.githubusercontent.com/75848483/118833581-2360a780-b8f4-11eb-9e4e-8c1ff26218ce.png)

**Comment by Begeassgit** [comment]
It seemed like you need check your project in idea is using jdk11.0 or more higher version. You can change it by this: move your mouse on the project called “RepairWeb-master” and click the right button. There will have a list pop out and find the option called “Open module settings” , in there, you can change the default jdk to jdk 8 or 11.0 or higher editions.


看上去你需要检查你的项目是否包含了正确的jdk，这个项目需要使用 jdk11.0 或更高版本。你可以通过以下方式更改它：把鼠标放在名为“RepairWeb-master”的项目上，然后单击右键。将弹出一个列表，找到名为“ Open module settings”的选项，在那里，您可以将默认的 jdk 更改为 jdk 8 或 11.0 或更高版本。



iPhone
